service: default
runtime: python

env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3


instance_class: F4
network:
  instance_tag: isb-cgc-tp53

env_variables:
  BQ_DATASET: 'P53_data'
  DATA_VERSION: 'r20'


handlers:
- url: /.*
  script: auto
  secure: always